In [2]:
import numpy as np

Problem  1

Convert a 1D array to a 2D array with 2 rows

Input:
```
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```



In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.shape = ((2, 5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
res= x.reshape(2, 5)
res

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np

Problem  2

Extract all odd numbers from arr

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```



In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
delete_odd = np.delete(arr, arr[1::2])
delete_odd

array([0, 2, 4, 6, 8])

Problem  3

Replace all odd numbers in arr with -1

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```



In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[1::2] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Problem  4

Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

```
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```




In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr1 = arr[:]

arr1[1::2]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Problem  5

Stack arrays a and b vertically

Input



```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:


```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```




In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#you can also do vstack
ver = np.row_stack((a, b))
ver


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Problem  6

Stack the arrays a and b horizontally.

Input


```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:



```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```




In [29]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

hor = np.column_stack((a,b))
hor


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Problem  7

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:



```
a = np.array([1,2,3])
```


Desired Output:



```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```




In [30]:
a = np.array([1,2,3])

new_a = np.insert(a, [-1, -1, -2, -2, -3, -3], [3, 3, 2, 2, 1, 1])


new_a = np.append(new_a, [1,2,3,1,2,3,1,2,3])
new_a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Problem  8

From array a remove all items present in array b

Input:


```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired Output:

```
array([1,2,3,4])
```




In [41]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

b = np.delete(b, np.s_[:])
print(a)
print(b)

[1 2 3 4 5]
[]


Problem  9

Get the positions where elements of a and b match

Input:



```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```


Desired Output:



```
(array([1, 3, 5, 7]),)
```



In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])



(0,) 1
(1,) 2
(2,) 3
(3,) 2
(4,) 3
(5,) 4
(6,) 3
(7,) 4
(8,) 5
(9,) 6


Problem  10

Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
```

Output:



```
array([[1, 0, 2],
      [4, 3, 5],
      [7, 6, 8]])
```




In [68]:
arr = np.arange(9).reshape(3,3)
arr[:, [0, 1]] = arr[:, [1, 0]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Problem  11

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

Input:


```
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```


Problem  12

Compute the counts of unique values row-wise.

Input:



```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```



Desired Output:



```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```



In [8]:
import numpy as np
np.random.seed(100)
a = np.random.uniform(1,50, 20)
# a
np.where(a[:] > 30, '30', '10')

array(['10', '10', '10', '30', '10', '10', '30', '30', '10', '10', '30',
       '10', '10', '10', '10', '30', '30', '10', '30', '10'], dtype='<U2')

Problem  13

Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [ ]:
# i don't understand the  dummy bin variables and one-hot-encoding

Problem  14

Create the ranks for the given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]
```

Desired output:

```
[4 2 6 0 8 7 9 3 5 1]
```

In [17]:
import numpy as np

# Input array
a = np.array([9, 4, 15, 0, 17, 16, 17, 8, 9, 0])
i = np.argsort(a)
# Compute the ranks
ranks = np.argsort(i)

print(ranks)

[4 2 6 0 8 7 9 3 5 1]


Problem  15

Create a rank array of the same shape as a given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]
```


Desired output:



```
#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]
```



In [32]:
# how to get same shape in output rank array

array([[2, 1, 3, 0, 4],
       [3, 4, 1, 2, 0]], dtype=int64)

Problem  16

Compute the min-by-max for each row for given 2d numpy array

Input:

```
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])
```

Desired Output:

```
array([ 0.44444444,  0.125     ,  0.5       ,  1.        ,  0.11111111])
```

In [4]:
import numpy as np
arr = np.array([[9, 9, 4], [8, 8, 1], [5, 3, 6], [3, 3, 3], [2, 1, 9]])
res = np.min(arr, axis=1) / np.max(arr, axis=1)
res

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

Problem  17

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False

Input
```
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> Array: [0 0 3 0 2 4 2 2 2 2]
```
Desired Output:
```
#> [False  True False  True False False  True  True  True  True]
```

Problem  18

Drop all nan values from a 1D numpy array

Input:
```
np.array([1,2,3,np.nan,5,6,7,np.nan])
```
Desired Output:
```
array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [41]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
delnan = np.isnan(a)

a2 = a[~delnan]
a2

array([nan, nan])

Problem 19

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```

In [46]:
import numpy as np
import scipy as sp

arr =  np.array([1, 3, 7, 1, 2, 6, 0, 1])

peaks= sp.signal.find_peaks(arr)
peaks

(array([2, 5], dtype=int64), {})

Problem 20

Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.


Input
```
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]

```
Desired Output:
```
#> [[2 2 2]
#>  [2 2 2]
#>  [2 2 2]]
```

In [61]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
                
arr = a_2d[0] - b_1d
times = 3
a = np.tile(arr,(times, 1))
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

Problem 21

Find the index of 5th repetition of number 1 in x.

Input:

```
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```



In [16]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

two = 1

find_two = np.where(x == two)[0]

find_index = find_two[4]
find_index

8

Problem 22

Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

Problem 23

 From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:
```
arr = np.arange(15)
arr
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

Desired Output:
```
#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]
```